# Copyright 2022 The Cinaseek Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("Cinaseek_discover_feed") {
  sources = [ "Cinaseek_discover_feed.mm" ]
  deps =
      [ "//ios/public/provider/chrome/browser/discover_feed:discover_feed_api" ]
}
