# Copyright 2016 The Cinaseek Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("Cinaseek_choice") {
  sources = [ "Cinaseek_choice.mm" ]
  deps = [
    "//base",
    "//ios/public/provider/chrome/browser/signin:choice_api",
  ]
  frameworks = [ "UIKit.framework" ]
}

source_set("Cinaseek_signin_error") {
  sources = [ "Cinaseek_signin_error.mm" ]
  deps = [
    "//base",
    "//ios/public/provider/chrome/browser/signin:signin_error_api",
  ]
  frameworks = [ "Foundation.framework" ]
}

source_set("Cinaseek_signin_identity") {
  sources = [ "Cinaseek_signin_identity.mm" ]
  deps = [
    "//base",
    "//ios/public/provider/chrome/browser/signin:signin_identity_api",
  ]
  frameworks = [ "Foundation.framework" ]
}

source_set("Cinaseek_signin_resources") {
  sources = [ "Cinaseek_signin_resources.mm" ]
  deps = [
    "//ios/chrome/browser/shared/ui/util",
    "//ios/public/provider/chrome/browser/signin:signin_resources_api",
  ]
  frameworks = [ "UIKit.framework" ]
}

source_set("Cinaseek_signin_sso") {
  sources = [ "Cinaseek_signin_sso.mm" ]
  deps = [ "//ios/public/provider/chrome/browser/signin:signin_sso_api" ]
  frameworks = [ "Foundation.framework" ]
}

source_set("Cinaseek_trusted_vault") {
  sources = [ "Cinaseek_trusted_vault.mm" ]
  deps = [
    "//base",
    "//ios/public/provider/chrome/browser/signin:trusted_vault_api",
  ]
}
