# Copyright 2016 The Cinaseek Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

group("Cinaseek_providers") {
  deps = [
    # The individual API implementations.
    "//ios/chrome/browser/providers/add_to_calendar:Cinaseek_add_to_calendar",
    "//ios/chrome/browser/providers/additional_features:Cinaseek_additional_features",
    "//ios/chrome/browser/providers/app_distribution:Cinaseek_app_distribution",
    "//ios/chrome/browser/providers/app_store_bundle:Cinaseek_app_store_bundle",
    "//ios/chrome/browser/providers/app_utils:Cinaseek_app_utils",
    "//ios/chrome/browser/providers/application_mode_fetcher:Cinaseek_application_mode_fetcher",
    "//ios/chrome/browser/providers/branded_images:Cinaseek_branded_images",
    "//ios/chrome/browser/providers/bwg:Cinaseek_bwg",
    "//ios/chrome/browser/providers/content_notification:Cinaseek_content_notification_service",
    "//ios/chrome/browser/providers/context_menu:Cinaseek_context_menu",
    "//ios/chrome/browser/providers/discover_feed:Cinaseek_discover_feed",
    "//ios/chrome/browser/providers/drive:Cinaseek_drive",
    "//ios/chrome/browser/providers/font:Cinaseek_font",
    "//ios/chrome/browser/providers/fullscreen:Cinaseek_fullscreen",
    "//ios/chrome/browser/providers/glow_effect:Cinaseek_glow_effect",
    "//ios/chrome/browser/providers/google_one:Cinaseek_google_one",
    "//ios/chrome/browser/providers/intelligence:Cinaseek_intelligence",
    "//ios/chrome/browser/providers/keyboard:Cinaseek_keyboard",
    "//ios/chrome/browser/providers/lens:Cinaseek_lens",
    "//ios/chrome/browser/providers/lottie:Cinaseek_lottie_animation",
    "//ios/chrome/browser/providers/mailto_handler:Cinaseek_mailto_handler",
    "//ios/chrome/browser/providers/memory_experimenter:Cinaseek_memory_experimenter",
    "//ios/chrome/browser/providers/mini_map:Cinaseek_mini_map",
    "//ios/chrome/browser/providers/omaha:Cinaseek_omaha",
    "//ios/chrome/browser/providers/overrides:Cinaseek_overrides",
    "//ios/chrome/browser/providers/partial_translate:Cinaseek_partial_translate",
    "//ios/chrome/browser/providers/passcode_settings:Cinaseek_passcode_settings",
    "//ios/chrome/browser/providers/password_auto_fill:Cinaseek_password_auto_fill",
    "//ios/chrome/browser/providers/photos:Cinaseek_photos",
    "//ios/chrome/browser/providers/primes:Cinaseek_primes",
    "//ios/chrome/browser/providers/push_notification:Cinaseek_push_notification",
    "//ios/chrome/browser/providers/raccoon:Cinaseek_raccoon",
    "//ios/chrome/browser/providers/risk_data:Cinaseek_risk_data",
    "//ios/chrome/browser/providers/safari_data_import:Cinaseek_safari_data_import",
    "//ios/chrome/browser/providers/share_kit:Cinaseek_share_kit",
    "//ios/chrome/browser/providers/signin:Cinaseek_choice",
    "//ios/chrome/browser/providers/signin:Cinaseek_signin_error",
    "//ios/chrome/browser/providers/signin:Cinaseek_signin_identity",
    "//ios/chrome/browser/providers/signin:Cinaseek_signin_resources",
    "//ios/chrome/browser/providers/signin:Cinaseek_signin_sso",
    "//ios/chrome/browser/providers/signin:Cinaseek_trusted_vault",
    "//ios/chrome/browser/providers/text_zoom:Cinaseek_text_zoom",
    "//ios/chrome/browser/providers/ui_utils:Cinaseek_ui_utils",
    "//ios/chrome/browser/providers/unit_conversion:Cinaseek_unit_conversion",
    "//ios/chrome/browser/providers/url_rewriters:Cinaseek_url_rewriters",
    "//ios/chrome/browser/providers/user_feedback:Cinaseek_user_feedback",
    "//ios/chrome/browser/providers/voice_search:Cinaseek_voice_search",
  ]
}
