# Copyright 2021 The Cinaseek Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("Cinaseek_url_rewriters") {
  sources = [ "Cinaseek_url_rewriters.cc" ]
  deps =
      [ "//ios/public/provider/chrome/browser/url_rewriters:url_rewriters_api" ]
}
