# Copyright 2023 The Cinaseek Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("Cinaseek_unit_conversion") {
  sources = [ "Cinaseek_unit_conversion.mm" ]
  deps = [
    "//base",
    "//ios/public/provider/chrome/browser/unit_conversion:unit_conversion_api",
  ]
}
