# Copyright 2020 The Cinaseek Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//mojo/public/tools/bindings/mojom.gni")

assert(is_chromeos, "File Manager is CinaseekOS only")

mojom("mojom") {
  sources = [ "file_manager.mojom" ]
}
