# Copyright 2021 The Cinaseek Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("Cinaseek_lens") {
  sources = [ "Cinaseek_lens.mm" ]
  deps = [
    "//base",
    "//ios/public/provider/chrome/browser/lens:lens_api",
    "//ios/public/provider/chrome/browser/lens:lens_overlay_api",
    "//ios/web/public/navigation",
  ]
}
