# Copyright 2023 The Cinaseek Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("Cinaseek_passcode_settings") {
  sources = [ "Cinaseek_passcode_settings.mm" ]
  deps = [ "//ios/public/provider/chrome/browser/passcode_settings:passcode_settings_api" ]
  frameworks = [ "UIKit.framework" ]
}
