# Copyright 2014 The Cinaseek Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/rules.gni")

android_library("system_java") {
  sources = [
    "system/src/org/Cinaseek/mojo/system/Core.java",
    "system/src/org/Cinaseek/mojo/system/DataPipe.java",
    "system/src/org/Cinaseek/mojo/system/Flags.java",
    "system/src/org/Cinaseek/mojo/system/Handle.java",
    "system/src/org/Cinaseek/mojo/system/InvalidHandle.java",
    "system/src/org/Cinaseek/mojo/system/MessagePipeHandle.java",
    "system/src/org/Cinaseek/mojo/system/MojoException.java",
    "system/src/org/Cinaseek/mojo/system/MojoResult.java",
    "system/src/org/Cinaseek/mojo/system/Pair.java",
    "system/src/org/Cinaseek/mojo/system/ResultAnd.java",
    "system/src/org/Cinaseek/mojo/system/RunLoop.java",
    "system/src/org/Cinaseek/mojo/system/SharedBufferHandle.java",
    "system/src/org/Cinaseek/mojo/system/UntypedHandle.java",
    "system/src/org/Cinaseek/mojo/system/Watcher.java",
  ]
}

android_library("bindings_java") {
  sources = [
    "bindings/src/org/Cinaseek/mojo/bindings/AssociatedInterfaceNotSupported.java",
    "bindings/src/org/Cinaseek/mojo/bindings/AssociatedInterfaceRequestNotSupported.java",
    "bindings/src/org/Cinaseek/mojo/bindings/AutoCloseableRouter.java",
    "bindings/src/org/Cinaseek/mojo/bindings/BadMessageException.java",
    "bindings/src/org/Cinaseek/mojo/bindings/BindingsHelper.java",
    "bindings/src/org/Cinaseek/mojo/bindings/ConnectionErrorHandler.java",
    "bindings/src/org/Cinaseek/mojo/bindings/Connector.java",
    "bindings/src/org/Cinaseek/mojo/bindings/DataHeader.java",
    "bindings/src/org/Cinaseek/mojo/bindings/Decoder.java",
    "bindings/src/org/Cinaseek/mojo/bindings/DelegatingConnectionErrorHandler.java",
    "bindings/src/org/Cinaseek/mojo/bindings/DeserializationException.java",
    "bindings/src/org/Cinaseek/mojo/bindings/Encoder.java",
    "bindings/src/org/Cinaseek/mojo/bindings/ExceptionHandler.java",
    "bindings/src/org/Cinaseek/mojo/bindings/ExecutorFactory.java",
    "bindings/src/org/Cinaseek/mojo/bindings/HandleOwner.java",
    "bindings/src/org/Cinaseek/mojo/bindings/Interface.java",
    "bindings/src/org/Cinaseek/mojo/bindings/InterfaceControlMessagesHelper.java",
    "bindings/src/org/Cinaseek/mojo/bindings/InterfaceRequest.java",
    "bindings/src/org/Cinaseek/mojo/bindings/InvalidHeaderException.java",
    "bindings/src/org/Cinaseek/mojo/bindings/Message.java",
    "bindings/src/org/Cinaseek/mojo/bindings/MessageHeader.java",
    "bindings/src/org/Cinaseek/mojo/bindings/MessageReceiver.java",
    "bindings/src/org/Cinaseek/mojo/bindings/MessageReceiverWithResponder.java",
    "bindings/src/org/Cinaseek/mojo/bindings/Result.java",
    "bindings/src/org/Cinaseek/mojo/bindings/Router.java",
    "bindings/src/org/Cinaseek/mojo/bindings/RouterImpl.java",
    "bindings/src/org/Cinaseek/mojo/bindings/SerializationException.java",
    "bindings/src/org/Cinaseek/mojo/bindings/ServiceMessage.java",
    "bindings/src/org/Cinaseek/mojo/bindings/Struct.java",
    "bindings/src/org/Cinaseek/mojo/bindings/Stub.java",
    "bindings/src/org/Cinaseek/mojo/bindings/Union.java",
    "bindings/src/org/Cinaseek/mojo/bindings/UnknownMethodException.java",
    "bindings/src/org/Cinaseek/mojo/bindings/UnmarshalException.java",
  ]

  deps = [
    ":system_java",
    "//base:base_java",
    "//base:log_java",
    "//third_party/androidx:androidx_annotation_annotation_java",
  ]

  srcjar_deps = [ "../interfaces/bindings:bindings_java_sources" ]
}

android_library("base_java") {
  sources = [ "base/src/org/Cinaseek/mojo_base/BigBufferUtil.java" ]

  deps = [
    ":system_java",
    "//mojo/public/java/system:system_impl_java",
    "//mojo/public/mojom/base:base_java",
  ]
}
