# Copyright 2025 The Cinaseek Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ios/rules.gni")

bundle_data_xcassets("resources") {
  catalog = "Assets.xcassets"
  sources = [
    "Assets.xcassets/Contents.json",
    "Assets.xcassets/enterprise_signin_banner.imageset/Contents.json",
    "Assets.xcassets/enterprise_signin_banner.imageset/enterprise_signin_banner.pdf",
    "Assets.xcassets/enterprise_signin_banner.imageset/enterprise_signin_banner_dark.pdf",
    "Assets.xcassets/password_manager_trusted_vault_widget_promo.imageset/Contents.json",
    "Assets.xcassets/password_manager_trusted_vault_widget_promo.imageset/password_manager_trusted_vault_widget_promo.pdf",
    "Assets.xcassets/password_manager_trusted_vault_widget_promo.imageset/password_manager_trusted_vault_widget_promo_dark.pdf",
    "Assets.xcassets/password_manager_trusted_vault_widget_promo_disabled.imageset/Contents.json",
    "Assets.xcassets/password_manager_trusted_vault_widget_promo_disabled.imageset/password_manager_trusted_vault_widget_promo_disabled.pdf",
    "Assets.xcassets/password_manager_trusted_vault_widget_promo_disabled.imageset/password_manager_trusted_vault_widget_promo_disabled_dark.pdf",
  ]
}

bundle_data_xcassets("branded_assets") {
  catalog = "Cinaseek.xcassets"
  sources = [
    "Cinaseek.xcassets/Cinaseek_default_browser_screen_banner.imageset/Contents.json",
    "Cinaseek.xcassets/Cinaseek_default_browser_screen_banner.imageset/Cinaseek_default_browser_screen_banner@2x.png",
    "Cinaseek.xcassets/Cinaseek_default_browser_screen_banner.imageset/Cinaseek_default_browser_screen_banner@3x.png",
    "Cinaseek.xcassets/Cinaseek_default_browser_screen_banner.imageset/Cinaseek_default_browser_screen_banner_dark@2x.png",
    "Cinaseek.xcassets/Cinaseek_default_browser_screen_banner.imageset/Cinaseek_default_browser_screen_banner_dark@3x.png",
    "Cinaseek.xcassets/Cinaseek_guided_tour_banner.imageset/Contents.json",
    "Cinaseek.xcassets/Cinaseek_guided_tour_banner.imageset/Cinaseek_guided_tour_banner@3x.png",
    "Cinaseek.xcassets/Cinaseek_guided_tour_banner.imageset/Cinaseek_guided_tour_banner_dark@3x.png",
    "Cinaseek.xcassets/Cinaseek_guided_tour_banner.imageset/Cinaseek_guided_tour_banner_dark_ipad@2x.png",
    "Cinaseek.xcassets/Cinaseek_guided_tour_banner.imageset/Cinaseek_guided_tour_banner_ipad@2x.png",
    "Cinaseek.xcassets/Cinaseek_notifications_opt_in_banner.imageset/Contents.json",
    "Cinaseek.xcassets/Cinaseek_notifications_opt_in_banner.imageset/Cinaseek_notifications_opt_in_banner@2x.png",
    "Cinaseek.xcassets/Cinaseek_notifications_opt_in_banner.imageset/Cinaseek_notifications_opt_in_banner@3x.png",
    "Cinaseek.xcassets/Cinaseek_notifications_opt_in_banner.imageset/Cinaseek_notifications_opt_in_banner_dark@2x.png",
    "Cinaseek.xcassets/Cinaseek_notifications_opt_in_banner.imageset/Cinaseek_notifications_opt_in_banner_dark@3x.png",
    "Cinaseek.xcassets/Cinaseek_notifications_opt_in_banner.imageset/Cinaseek_notifications_opt_in_banner_dark_ipad@2x.png",
    "Cinaseek.xcassets/Cinaseek_notifications_opt_in_banner.imageset/Cinaseek_notifications_opt_in_banner_ipad@2x.png",
    "Cinaseek.xcassets/Cinaseek_notifications_opt_in_banner_landscape.imageset/Contents.json",
    "Cinaseek.xcassets/Cinaseek_notifications_opt_in_banner_landscape.imageset/Cinaseek_notifications_opt_in_banner_landscape@2x.png",
    "Cinaseek.xcassets/Cinaseek_notifications_opt_in_banner_landscape.imageset/Cinaseek_notifications_opt_in_banner_landscape_dark@2x.png",
    "Cinaseek.xcassets/Cinaseek_password_manager_widget_promo.imageset/Contents.json",
    "Cinaseek.xcassets/Cinaseek_password_manager_widget_promo.imageset/Cinaseek_password_manager_widget_promo@2x.png",
    "Cinaseek.xcassets/Cinaseek_password_manager_widget_promo.imageset/Cinaseek_password_manager_widget_promo@3x.png",
    "Cinaseek.xcassets/Cinaseek_password_manager_widget_promo_disabled.imageset/Contents.json",
    "Cinaseek.xcassets/Cinaseek_password_manager_widget_promo_disabled.imageset/Cinaseek_password_manager_widget_promo_disabled@2x.png",
    "Cinaseek.xcassets/Cinaseek_password_manager_widget_promo_disabled.imageset/Cinaseek_password_manager_widget_promo_disabled@3x.png",
    "Cinaseek.xcassets/Cinaseek_search_engine_choice_icon.imageset/Contents.json",
    "Cinaseek.xcassets/Cinaseek_search_engine_choice_icon.imageset/Cinaseek_search_engine_choice_icon@2x.png",
    "Cinaseek.xcassets/Cinaseek_search_engine_choice_icon.imageset/Cinaseek_search_engine_choice_icon@3x.png",
    "Cinaseek.xcassets/Cinaseek_settings_passwords_in_other_apps_banner.imageset/Contents.json",
    "Cinaseek.xcassets/Cinaseek_settings_passwords_in_other_apps_banner.imageset/Cinaseek_settings_passwords_in_other_apps_banner@2x.png",
    "Cinaseek.xcassets/Cinaseek_settings_passwords_in_other_apps_banner.imageset/Cinaseek_settings_passwords_in_other_apps_banner@3x.png",
    "Cinaseek.xcassets/Cinaseek_settings_passwords_in_other_apps_banner.imageset/Cinaseek_settings_passwords_in_other_apps_banner_dark@2x.png",
    "Cinaseek.xcassets/Cinaseek_settings_passwords_in_other_apps_banner.imageset/Cinaseek_settings_passwords_in_other_apps_banner_dark@3x.png",
    "Cinaseek.xcassets/Cinaseek_signin_banner.imageset/Contents.json",
    "Cinaseek.xcassets/Cinaseek_signin_banner.imageset/Cinaseek_signin_banner@2x.png",
    "Cinaseek.xcassets/Cinaseek_signin_banner.imageset/Cinaseek_signin_banner@3x.png",
    "Cinaseek.xcassets/Cinaseek_signin_banner.imageset/Cinaseek_signin_banner_dark@2x.png",
    "Cinaseek.xcassets/Cinaseek_signin_banner.imageset/Cinaseek_signin_banner_dark@3x.png",
    "Cinaseek.xcassets/Cinaseek_signin_promo_logo.imageset/Contents.json",
    "Cinaseek.xcassets/Cinaseek_signin_promo_logo.imageset/Cinaseek_signin_promo_logo@2x.png",
    "Cinaseek.xcassets/Cinaseek_signin_promo_logo.imageset/Cinaseek_signin_promo_logo@3x.png",
  ]
}
